// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkIRvfUSuPbsFYaI1JvPcdqlhNj5RTrCg',
    appId: '1:776568219977:web:f60ca39495cc773045d298',
    messagingSenderId: '776568219977',
    projectId: 'fir-chat-52f56',
    authDomain: 'fir-chat-52f56.firebaseapp.com',
    storageBucket: 'fir-chat-52f56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmQTFTzLrlDXkEyFK5QNHxaS_rhQsNUk',
    appId: '1:776568219977:android:d8de1d9c8f677da045d298',
    messagingSenderId: '776568219977',
    projectId: 'fir-chat-52f56',
    storageBucket: 'fir-chat-52f56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-8J-OAj46Dkw-eRNqbVI6Mu28hwOQBE',
    appId: '1:776568219977:ios:118f6f874d40008645d298',
    messagingSenderId: '776568219977',
    projectId: 'fir-chat-52f56',
    storageBucket: 'fir-chat-52f56.appspot.com',
    androidClientId: '776568219977-1ucura2vs71hce97al0viq0jvtinktgk.apps.googleusercontent.com',
    iosClientId: '776568219977-bcjqst6irfotsqakppb46iflukeinmi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-8J-OAj46Dkw-eRNqbVI6Mu28hwOQBE',
    appId: '1:776568219977:ios:118f6f874d40008645d298',
    messagingSenderId: '776568219977',
    projectId: 'fir-chat-52f56',
    storageBucket: 'fir-chat-52f56.appspot.com',
    androidClientId: '776568219977-1ucura2vs71hce97al0viq0jvtinktgk.apps.googleusercontent.com',
    iosClientId: '776568219977-bcjqst6irfotsqakppb46iflukeinmi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappfirebase',
  );
}
